apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: image
      #- image: dockersamples/examplevotingapp_worker
        name: worker
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            memory: "128Mi"
            cpu: "300m"
