# Default values for worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
worker:
  image:
    name: worker
    repository: "192.168.157.4:32380"
    project: demo
    tag: sprint_0001-2e5278a
result:
  image:
    name: result
    repository: "192.168.157.4:32380"
    project: demo
    tag: sprint_0001-677f089
vote:
  image:
    name: vote
    repository: "192.168.157.4:32380"
    project: demo
    tag: sprint_0001-2f9e17b
service:
  type: ClusterIP
  port: 80
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
