apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: image
        name: result
        ports:
        - containerPort: 80
          name: result
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            memory: "128Mi"
            cpu: "300m"
